apiVersion: apps/v1
kind: Deployment
metadata:
  name: do-kubernetes-sample-app1
  namespace: default
  labels:
    app: do-kubernetes-sample-app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: do-kubernetes-sample-app1
  template:
    metadata:
      labels:
        app: do-kubernetes-sample-app1
    spec:
      containers:
        - name: do-kubernetes-sample-app1
          image: 0676860787/do-kubernetes-sample-app1:latest
          ports:
            - containerPort: 80
              name: http
        
